- qdrant/v0.6.x/collections.md
commit for testing a lang switcher
> python example for collections

- qdrant/v0.8.x/collections.md
- qdrant/v0.8.x/filtering.md
- qdrant/v0.8.x/indexing.md
- qdrant/v0.8.x/payload.md
- qdrant/v0.8.x/points.md
- qdrant/v0.8.x/quick_start.md
- qdrant/v0.8.x/search.md
Some of the Python examples I created. Some of the methods are still not exposed to the main client, and those were not documented.
> [WIP] V0.8.0 python client examples

- qdrant/v0.8.x/snapshots.md
This PR introduces a basic documentation for the new snapshot API.
> Snapshot API docs

- qdrant/v0.10.x/_index.md
- qdrant/v0.10.x/collections.md
- qdrant/v0.10.x/configuration.md
- qdrant/v0.10.x/distributed_deployment.md
- qdrant/v0.10.x/filtering.md
- qdrant/v0.10.x/indexing.md
- qdrant/v0.10.x/install.md
- qdrant/v0.10.x/optimizer.md
- qdrant/v0.10.x/payload.md
- qdrant/v0.10.x/points.md
- qdrant/v0.10.x/quick_start.md
- qdrant/v0.10.x/search.md
- qdrant/v0.10.x/snapshots.md
- qdrant/v0.10.x/storage.md
This PR fixes a bunch of markdown issues reported locally by a linter.
> markdown formatting according to linter

- qdrant/v0.11.0.x/_index.md
- qdrant/v0.11.0.x/clients.md
- qdrant/v0.11.0.x/collections.md
- qdrant/v0.11.0.x/configuration.md
- qdrant/v0.11.0.x/distributed_deployment.md
- qdrant/v0.11.0.x/filtering.md
- qdrant/v0.11.0.x/indexing.md
- qdrant/v0.11.0.x/install.md
- qdrant/v0.11.0.x/optimizer.md
- qdrant/v0.11.0.x/payload.md
- qdrant/v0.11.0.x/points.md
- qdrant/v0.11.0.x/quick_start.md
- qdrant/v0.11.0.x/quick_start_python.md
- qdrant/v0.11.0.x/search.md
- qdrant/v0.11.0.x/snapshots.md
- qdrant/v0.11.0.x/storage.md
Introduce new `v0.11.x` folder containing a copy of `v0.10.x`.
> Initialize v0.11.x docs

- qdrant/v0.10.x/distributed_deployment.md
- qdrant/v0.11.0.x/distributed_deployment.md
Added some missing quotation marks in the HTTP request examples
> Add missing quotation marks in distributed deployment

- qdrant/v0.11.x/distributed_deployment.md
- qdrant/v0.11.x/install.md
- qdrant/v0.11.x/integrations.md
All the currently existing and future integrations are put into a separate docs section.
> Move integrations into separate section

- qdrant/v0.11.x/cloud.md
I created a new section for Qdrant Cloud
> Add Qdrant Cloud api-key info

- qdrant/v0.11.x/collections.md
This is an extended description of the indexed_vectors_count and why it might be lower than expected.
> Add more information about the indexed_vectors_count property

- qdrant/v0.11.x/integrations.md
I discussed the description of the Aleph Alpha with Piotr and he asked to make those changes.
> Fix Aleph Alpha description after their feedback

- qdrant/v1.0.x/collections.md
- qdrant/v1.0.x/snapshots.md
- Rust client https://github.com/qdrant/rust-client/pull/17
> Docs for list aliases & delete snapshots

- qdrant/v1.0.x/collections.md
Adding missing doc for collection init from.
> add docs for collection init from

- qdrant/v1.1.x/collections.md
Getting all collections are missing from the documentation
> Add get all collections

- qdrant/v1.1.x/integrations.md
This PR adds both LangChain and LlamaIndex into the integrations. Previously I opened PRs in the wrong repo.
> Add LangChain and LlamaIndex into integrations

- qdrant/v1.1.x/configuration.md
This updates the example configuration to pick the latest from `master`: https://github.com/qdrant/qdrant/blob/master/config/config.yaml
> Update example configuration to match changes in v1.1.1

- qdrant/v1.1.x/integrations.md
A short update about the Haystack integration: this will be announced soon by the Deepset team.
> Add info about Haystack integration

- qdrant/v1.1.x/integrations.md
This is a short piece of info on the recent integration that the FiftyOne team has made.
> Add info about FiftyOne integration

- qdrant/v1.1.x/points.md
I'm adding an alternative way of modifying the payload using filters. As requested on Discord: https://discord.com/channels/907569970500743200/928649303898075196/1106948171382399006
> Add alternative way of modyfing the payload, using filters

- qdrant/v1.1.x/how_to.md
Adding a solution to the "Error: Too many files open (OS error 24)". Suggested only Docker-related solution, as there seem to be various ways, and those might be googled easily.
> Add a solution to "Too many file open" error

- qdrant/v1.2.x/search.md
> Add Grouping API documentation

- qdrant/v1.2.x/filtering.md
Documentation for https://github.com/qdrant/qdrant/pull/1602
I have generated the Python client to double check the types.
> Nested object filter

- qdrant/v1.1.x/monitoring.md
- qdrant/v1.1.x/telemetry.md
- qdrant/v1.2.x/monitoring.md
- qdrant/v1.2.x/telemetry.md
This PR introduces a separate section for monitoring, with a description of all the metrics. Those were taken from the codebase (master branch), so publishing after the next release might be better.
> Monitoring section

- qdrant/v0.10.x/collections.md
- qdrant/v0.11.x/collections.md
- qdrant/v0.3.x/collections.md
- qdrant/v0.5.x/collections.md
- qdrant/v0.6.x/collections.md
- qdrant/v0.7.x/collections.md
- qdrant/v0.8.x/collections.md
- qdrant/v0.9.x/collections.md
- qdrant/v1.0.x/collections.md
- qdrant/v1.1.x/collections.md
- qdrant/v1.2.x/collections.md
Fixes <https://github.com/qdrant/docs/issues/68>.
> Improve collections sentence describing distance metrics

- qdrant/v1.1.x/integrations.md
- qdrant/v1.2.x/integrations.md
The previous link was pointing to a non-existent notebook
> Fix Llama Index notebook link
